// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/universities.proto

package universities

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Universities service

func NewUniversitiesEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Universities service

type UniversitiesService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Universities_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Universities_PingPongService, error)
}

type universitiesService struct {
	c    client.Client
	name string
}

func NewUniversitiesService(name string, c client.Client) UniversitiesService {
	return &universitiesService{
		c:    c,
		name: name,
	}
}

func (c *universitiesService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Universities.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *universitiesService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Universities_StreamService, error) {
	req := c.c.NewRequest(c.name, "Universities.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &universitiesServiceStream{stream}, nil
}

type Universities_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type universitiesServiceStream struct {
	stream client.Stream
}

func (x *universitiesServiceStream) Close() error {
	return x.stream.Close()
}

func (x *universitiesServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *universitiesServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *universitiesServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *universitiesServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *universitiesService) PingPong(ctx context.Context, opts ...client.CallOption) (Universities_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Universities.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &universitiesServicePingPong{stream}, nil
}

type Universities_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type universitiesServicePingPong struct {
	stream client.Stream
}

func (x *universitiesServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *universitiesServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *universitiesServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *universitiesServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *universitiesServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *universitiesServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Universities service

type UniversitiesHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Universities_StreamStream) error
	PingPong(context.Context, Universities_PingPongStream) error
}

func RegisterUniversitiesHandler(s server.Server, hdlr UniversitiesHandler, opts ...server.HandlerOption) error {
	type universities interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Universities struct {
		universities
	}
	h := &universitiesHandler{hdlr}
	return s.Handle(s.NewHandler(&Universities{h}, opts...))
}

type universitiesHandler struct {
	UniversitiesHandler
}

func (h *universitiesHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.UniversitiesHandler.Call(ctx, in, out)
}

func (h *universitiesHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.UniversitiesHandler.Stream(ctx, m, &universitiesStreamStream{stream})
}

type Universities_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type universitiesStreamStream struct {
	stream server.Stream
}

func (x *universitiesStreamStream) Close() error {
	return x.stream.Close()
}

func (x *universitiesStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *universitiesStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *universitiesStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *universitiesStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *universitiesHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.UniversitiesHandler.PingPong(ctx, &universitiesPingPongStream{stream})
}

type Universities_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type universitiesPingPongStream struct {
	stream server.Stream
}

func (x *universitiesPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *universitiesPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *universitiesPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *universitiesPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *universitiesPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *universitiesPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
